const countryList = {
  AED: { name: " - (United Arab Emirates Dirham)", flag: "AE" },
  AFN: { name: " - (Afghan Afghani)", flag: "AF" },
  XCD: { name: " - (East Caribbean Dollar)", flag: "AG" },
  ALL: { name: " - (Albanian Lek)", flag: "AL" },
  AMD: { name: " - (Armenian Dram)", flag: "AM" },
  ANG: { name: " - (Netherlands Antillean Guilder)", flag: "AN" },
  AOA: { name: " - (Angolan Kwanza)", flag: "AO" },
  AQD: { name: " - (Antarctica)", flag: "AQ" },
  ARS: { name: " - (Argentine Peso)", flag: "AR" },
  AUD: { name: " - (Australian Dollar)", flag: "AU" },
  AZN: { name: " - (Azerbaijani Manat)", flag: "AZ" },
  BAM: { name: " - (Bosnia and Herzegovina Convertible Marka)", flag: "BA" },
  BBD: { name: " - (Barbadian Dollar)", flag: "BB" },
  BDT: { name: " - (Bangladeshi Taka)", flag: "BD" },
  XOF: { name: " - (CFA Franc BCEAO)", flag: "BE" },
  BGN: { name: " - (Bulgarian Lev)", flag: "BG" },
  BHD: { name: " - (Bahraini Dinar)", flag: "BH" },
  BIF: { name: " - (Burundian Franc)", flag: "BI" },
  BMD: { name: " - (Bermudian Dollar)", flag: "BM" },
  BND: { name: " - (Brunei Dollar)", flag: "BN" },
  BOB: { name: " - (Bolivian Boliviano)", flag: "BO" },
  BRL: { name: " - (Brazilian Real)", flag: "BR" },
  BSD: { name: " - (Bahamian Dollar)", flag: "BS" },
  NOK: { name: " - (Norwegian Krone)", flag: "BV" },
  BWP: { name: " - (Botswana Pula)", flag: "BW" },
  BYR: { name: " - (Belarusian Ruble)", flag: "BY" },
  BZD: { name: " - (Belize Dollar)", flag: "BZ" },
  CAD: { name: " - (Canadian Dollar)", flag: "CA" },
  CDF: { name: " - (Congolese Franc)", flag: "CD" },
  XAF: { name: " - (CFA Franc BEAC)", flag: "CF" },
  CHF: { name: " - (Swiss Franc)", flag: "CH" },
  CLP: { name: " - (Chilean Peso)", flag: "CL" },
  CNY: { name: " - (Chinese Yuan)", flag: "CN" },
  COP: { name: " - (Colombian Peso)", flag: "CO" },
  CRC: { name: " - (Costa Rican Colón)", flag: "CR" },
  CUP: { name: " - (Cuban Peso)", flag: "CU" },
  CVE: { name: " - (Cape Verdean Escudo)", flag: "CV" },
  CYP: { name: " - (Cypriot Pound)", flag: "CY" },
  CZK: { name: " - (Czech Republic Koruna)", flag: "CZ" },
  DJF: { name: " - (Djiboutian Franc)", flag: "DJ" },
  DKK: { name: " - (Danish Krone)", flag: "DK" },
  DOP: { name: " - (Dominican Peso)", flag: "DO" },
  DZD: { name: " - (Algerian Dinar)", flag: "DZ" },
  ECS: { name: " - (Ecuadorian Sucre)", flag: "EC" },
  EEK: { name: " - (Estonian Kroon)", flag: "EE" },
  EGP: { name: " - (Egyptian Pound)", flag: "EG" },
  ETB: { name: " - (Ethiopian Birr)", flag: "ET" },
  EUR: { name: " - (Euro)", flag: "FR" },
  FJD: { name: " - (Fijian Dollar)", flag: "FJ" },
  FKP: { name: " - (Falkland Islands Pound)", flag: "FK" },
  GBP: { name: " - (British Pound Sterling)", flag: "GB" },
  GEL: { name: " - (Georgian Lari)", flag: "GE" },
  GGP: { name: " - (Guernsey Pound)", flag: "GG" },
  GHS: { name: " - (Ghanaian Cedi)", flag: "GH" },
  GIP: { name: " - (Gibraltar Pound)", flag: "GI" },
  GMD: { name: " - (Gambian Dalasi)", flag: "GM" },
  GNF: { name: " - (Guinean Franc)", flag: "GN" },
  GTQ: { name: " - (Guatemalan Quetzal)", flag: "GT" },
  GYD: { name: " - (Guyanaese Dollar)", flag: "GY" },
  HKD: { name: " - (Hong Kong Dollar)", flag: "HK" },
  HNL: { name: " - (Honduran Lempira)", flag: "HN" },
  HRK: { name: " - (Croatian Kuna)", flag: "HR" },
  HTG: { name: " - (Haitian Gourde)", flag: "HT" },
  HUF: { name: " - (Hungarian Forint)", flag: "HU" },
  IDR: { name: " - (Indonesian Rupiah)", flag: "ID" },
  INR: { name: " - (Indian Rupee)", flag: "IN" },
  IQD: { name: " - (Iraqi Dinar)", flag: "IQ" },
  IRR: { name: " - (Iranian Rial)", flag: "IR" },
  ISK: { name: " - (Icelandic Króna)", flag: "IS" },
  JMD: { name: " - (Jamaican Dollar)", flag: "JM" },
  JOD: { name: " - (Jordanian Dinar)", flag: "JO" },
  JPY: { name: " - (Japanese Yen)", flag: "JP" },
  KES: { name: " - (Kenyan Shilling)", flag: "KE" },
  KGS: { name: " - (Kyrgyzstani Som)", flag: "KG" },
  KHR: { name: " - (Cambodian Riel)", flag: "KH" },
  KMF: { name: " - (Comorian Franc)", flag: "KM" },
  KPW: { name: " - (North Korean Won)", flag: "KP" },
  KRW: { name: " - (South Korean Won)", flag: "KR" },
  KWD: { name: " - (Kuwaiti Dinar)", flag: "KW" },
  KYD: { name: " - (Cayman Islands Dollar)", flag: "KY" },
  KZT: { name: " - (Kazakhstani Tenge)", flag: "KZ" },
  LAK: { name: " - (Laotian Kip)", flag: "LA" },
  LBP: { name: " - (Lebanese Pound)", flag: "LB" },
  LKR: { name: " - (Sri Lankan Rupee)", flag: "LK" },
  LRD: { name: " - (Liberian Dollar)", flag: "LR" },
  LSL: { name: " - (Lesotho Loti)", flag: "LS" },
  LTL: { name: " - (Lithuanian Litas)", flag: "LT" },
  LVL: { name: " - (Latvian Lats)", flag: "LV" },
  LYD: { name: " - (Libyan Dinar)", flag: "LY" },
  MAD: { name: " - (Moroccan Dirham)", flag: "MA" },
  MDL: { name: " - (Moldovan Leu)", flag: "MD" },
  MGA: { name: " - (Malagasy Ariary)", flag: "MG" },
  MKD: { name: " - (Macedonian Denar)", flag: "MK" },
  MMK: { name: " - (Myanma Kyat)", flag: "MM" },
  MNT: { name: " - (Mongolian Tugrik)", flag: "MN" },
  MOP: { name: " - (Macanese Pataca)", flag: "MO" },
  MRO: { name: " - (Mauritanian Ouguiya)", flag: "MR" },
  MTL: { name: " - (Maltese Lira)", flag: "MT" },
  MUR: { name: " - (Mauritian Rupee)", flag: "MU" },
  MVR: { name: " - (Maldivian Rufiyaa)", flag: "MV" },
  MWK: { name: " - (Malawian Kwacha)", flag: "MW" },
  MXN: { name: " - (Mexican Peso)", flag: "MX" },
  MYR: { name: " - (Malaysian Ringgit)", flag: "MY" },
  MZN: { name: " - (Mozambican Metical)", flag: "MZ" },
  NAD: { name: " - (Namibian Dollar)", flag: "NA" },
  XPF: { name: " - (CFP Franc)", flag: "NC" },
  NGN: { name: " - (Nigerian Naira)", flag: "NG" },
  NIO: { name: " - (Nicaraguan Córdoba)", flag: "NI" },
  NPR: { name: " - (Nepalese Rupee)", flag: "NP" },
  NZD: { name: " - (New Zealand Dollar)", flag: "NZ" },
  OMR: { name: " - (Omani Rial)", flag: "OM" },
  PAB: { name: " - (Panamanian Balboa)", flag: "PA" },
  PEN: { name: " - (Peruvian Nuevo Sol)", flag: "PE" },
  PGK: { name: " - (Papua New Guinean Kina)", flag: "PG" },
  PHP: { name: " - (Philippine Peso)", flag: "PH" },
  PKR: { name: " - (Pakistani Rupee)", flag: "PK" },
  PLN: { name: " - (Polish Zloty)", flag: "PL" },
  PYG: { name: " - (Paraguayan Guarani)", flag: "PY" },
  QAR: { name: " - (Qatari Rial)", flag: "QA" },
  RON: { name: " - (Romanian Leu)", flag: "RO" },
  RSD: { name: " - (Serbian Dinar)", flag: "RS" },
  RUB: { name: " - (Russian Ruble)", flag: "RU" },
  RWF: { name: " - (Rwandan Franc)", flag: "RW" },
  SAR: { name: " - (Saudi Riyal)", flag: "SA" },
  SBD: { name: " - (Solomon Islands Dollar)", flag: "SB" },
  SCR: { name: " - (Seychellois Rupee)", flag: "SC" },
  SDG: { name: " - (Sudanese Pound)", flag: "SD" },
  SEK: { name: " - (Swedish Krona)", flag: "SE" },
  SGD: { name: " - (Singapore Dollar)", flag: "SG" },
  SKK: { name: " - (Slovak Koruna)", flag: "SK" },
  SLL: { name: " - (Sierra Leonean Leone)", flag: "SL" },
  SOS: { name: " - (Somali Shilling)", flag: "SO" },
  SRD: { name: " - (Surinamese Dollar)", flag: "SR" },
  STD: { name: " - (São Tomé and Príncipe Dobra)", flag: "ST" },
  SVC: { name: " - (Salvadoran Colón)", flag: "SV" },
  SYP: { name: " - (Syrian Pound)", flag: "SY" },
  SZL: { name: " - (Swazi Lilangeni)", flag: "SZ" },
  THB: { name: " - (Thai Baht)", flag: "TH" },
  TJS: { name: " - (Tajikistani Somoni)", flag: "TJ" },
  TMT: { name: " - (Turkmenistani Manat)", flag: "TM" },
  TND: { name: " - (Tunisian Dinar)", flag: "TN" },
  TOP: { name: " - (Tongan Pa'anga)", flag: "TO" },
  TRY: { name: " - (Turkish Lira)", flag: "TR" },
  TTD: { name: " - (Trinidad and Tobago Dollar)", flag: "TT" },
  TWD: { name: " - (New Taiwan Dollar)", flag: "TW" },
  TZS: { name: " - (Tanzanian Shilling)", flag: "TZ" },
  UAH: { name: " - (Ukrainian Hryvnia)", flag: "UA" },
  UGX: { name: " - (Ugandan Shilling)", flag: "UG" },
  USD: { name: " - (United States Dollar)", flag: "US" },
  UYU: { name: " - (Uruguayan Peso)", flag: "UY" },
  UZS: { name: " - (Uzbekistan Som)", flag: "UZ" },
  VEF: { name: " - (Venezuelan Bolívar Fuerte)", flag: "VE" },
  VND: { name: " - (Vietnamese Dong)", flag: "VN" },
  VUV: { name: " - (Vanuatu Vatu)", flag: "VU" },
  YER: { name: " - (Yemeni Rial)", flag: "YE" },
  ZAR: { name: " - (South African Rand)", flag: "ZA" },
  ZMK: { name: " - (Zambian Kwacha)", flag: "ZM" },
  ZWD: { name: " - (Zimbabwean Dollar)", flag: "ZW" },
};
